[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["cd backend && ./mvnw dependency:go-offline"]

[phases.build]
cmds = ["cd backend && ./mvnw clean package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/wordgame-0.0.1-SNAPSHOT.jar"