services:
  - type: web
    name: word-guessing-game-backend
    env: java
    region: oregon
    plan: free
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -jar target/wordgame-0.0.1-SNAPSHOT.jar
    healthCheckPath: /api/words/categories
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx512m